import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { RideStatus } from '../../models/ride.model';
export interface RideDraft { route: string; pickupLocation: string; pickupTime: string; vehicle: string; driver: string; status: RideStatus; }
@Component({ standalone: true, imports: [ReactiveFormsModule, MatDialogModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule], template: `<h2 mat-dialog-title>Add ride</h2><form [formGroup]="form" (ngSubmit)="submit()"><mat-dialog-content><mat-form-field appearance="outline"><mat-label>Route</mat-label><input matInput formControlName="route"><mat-error>Route is required.</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>Pickup location</mat-label><input matInput formControlName="pickupLocation"><mat-error>Pickup location is required.</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>Pickup time</mat-label><input matInput formControlName="pickupTime"><mat-error>Pickup time is required.</mat-error></mat-form-field><mat-form-field appearance="outline"><mat-label>Vehicle (optional)</mat-label><input matInput formControlName="vehicle"></mat-form-field><mat-form-field appearance="outline"><mat-label>Driver (optional)</mat-label><input matInput formControlName="driver"></mat-form-field><mat-form-field appearance="outline"><mat-label>Status</mat-label><mat-select formControlName="status"><mat-option value="On Time">On Time</mat-option><mat-option value="Delayed">Delayed</mat-option><mat-option value="Cancelled">Cancelled</mat-option></mat-select></mat-form-field></mat-dialog-content><mat-dialog-actions align="end"><button mat-button type="button" (click)="dialogRef.close()">Cancel</button><button mat-flat-button color="primary" type="submit">Add ride</button></mat-dialog-actions></form>`, styles: `mat-dialog-content{display:grid;grid-template-columns:1fr 1fr;gap:0 1rem;padding-top:.5rem}mat-form-field{width:100%}@media(max-width:560px){mat-dialog-content{grid-template-columns:1fr}}` })
export class AddRideDialogComponent { readonly dialogRef = inject(MatDialogRef<AddRideDialogComponent>); private readonly fb = inject(FormBuilder); readonly form = this.fb.nonNullable.group({ route: ['', Validators.required], pickupLocation: ['', Validators.required], pickupTime: ['', Validators.required], vehicle: [''], driver: [''], status: ['On Time' as RideStatus] }); submit(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.dialogRef.close(this.form.getRawValue()); } }
