import { Component, computed, inject, signal } from '@angular/core';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { debounceTime, distinctUntilChanged } from 'rxjs';
import { Ride, RideStatus } from '../../models/ride.model';
import { RideService } from '../../services/ride.service';
import { RideCardComponent } from '../../components/ride-card/ride-card.component';
import { AddRideDialogComponent, RideDraft } from './add-ride-dialog.component';
@Component({ standalone: true, imports: [ReactiveFormsModule, RideCardComponent, MatButtonModule, MatFormFieldModule, MatIconModule, MatInputModule, MatSelectModule], template: `<section class="heading"><div><p>COMMUTE SCHEDULE</p><h1>All rides</h1><span>Find and manage your upcoming commute.</span></div><button mat-flat-button color="primary" (click)="openAddRideDialog()"><mat-icon>add</mat-icon>Add ride</button></section><div class="filters"><mat-form-field appearance="outline"><mat-label>Search rides</mat-label><input matInput [formControl]="searchControl" placeholder="Search routes or pickup locations…"><mat-icon matPrefix>search</mat-icon></mat-form-field><mat-form-field appearance="outline"><mat-label>Status</mat-label><mat-select [value]="selectedFilter()" (selectionChange)="selectedFilter.set($event.value)"><mat-option value="All">All</mat-option><mat-option value="On Time">On Time</mat-option><mat-option value="Delayed">Delayed</mat-option><mat-option value="Cancelled">Cancelled</mat-option></mat-select></mat-form-field></div>@if (loading()) { <p class="state">Loading rides…</p> } @else if (error()) { <p class="state error">Unable to load rides. <button mat-button color="primary" (click)="load()">Try again</button></p> } @else if (!filteredRides().length) { <p class="state">No rides found.</p> } @else { <div class="ride-grid">@for (ride of filteredRides(); track ride.id) { <app-ride-card [ride]="ride" /> }</div> }`, styles: `.heading{display:flex;justify-content:space-between;gap:1rem;align-items:end}.heading p{color:#2563eb;font-weight:800;font-size:.76rem;letter-spacing:.08em;margin:0}.heading h1{color:#17243d;margin:.4rem 0}.heading span{color:#64748b}.filters{display:grid;grid-template-columns:1fr 190px;gap:1rem;margin:2rem 0}.filters mat-form-field{width:100%}.ride-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.state{padding:2rem;background:#fff;border-radius:12px;color:#64748b}.error{color:#b42318}@media(max-width:600px){.heading{align-items:start;flex-direction:column}.filters{grid-template-columns:1fr}.ride-grid{grid-template-columns:1fr}}` })
export class RidesComponent { private readonly service = inject(RideService); private readonly dialog = inject(MatDialog); readonly searchControl = new FormControl('', { nonNullable: true }); readonly rides = signal<Ride[]>([]); readonly selectedFilter = signal<'All' | RideStatus>('All'); readonly searchTerm = signal(''); readonly loading = signal(true); readonly error = signal(false); readonly filteredRides = computed(() => { const term = this.searchTerm().toLowerCase(); const status = this.selectedFilter(); return this.rides().filter(ride => (status === 'All' || ride.status === status) && `${ride.route} ${ride.pickupLocation}`.toLowerCase().includes(term)); }); constructor() { this.searchControl.valueChanges.pipe(debounceTime(250), distinctUntilChanged()).subscribe(value => this.searchTerm.set(value)); this.load(); } load(): void { this.loading.set(true); this.error.set(false); this.service.getRides().subscribe({ next: rides => { this.rides.set(rides); this.loading.set(false); }, error: () => { this.error.set(true); this.loading.set(false); } }); } openAddRideDialog(): void { this.dialog.open(AddRideDialogComponent, { width: '640px', maxWidth: 'calc(100vw - 32px)' }).afterClosed().subscribe((draft: RideDraft | undefined) => { if (draft) this.rides.update(rides => [...rides, this.service.addRide(draft)]); }); } }
